swagger: "2.0"
info:
  title: Blog API
  description: Simple blog app
  version: 1.0.0
host: localhost:8080
schemes:
  - http
  - https
paths:
  /api/v1/articles/all:
    get:
      summary: Get a list of all blog articles.
      description: Returns a list of all blog articles
      produces:
        - application/json
      responses:
        200:
          description: OK
